import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import BrandLogo from "../components/BrandLogo";

export default function Login() {
  const { login } = useAuth(); const navigate = useNavigate();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const handleSubmit = async (e) => { e.preventDefault(); setError(""); setLoading(true); try { await login(email, password); navigate("/"); } catch (err) { setError(err.response?.data?.detail || "Login failed. Please check your credentials."); } finally { setLoading(false); } };
  return <div className="min-h-screen flex items-center justify-center bg-brand-900 bg-[radial-gradient(circle_at_top_right,_rgba(245,144,26,.27),_transparent_30%),radial-gradient(circle_at_bottom_left,_rgba(19,139,52,.24),_transparent_40%)] px-4"><div className="w-full max-w-md"><div className="mb-7 text-center text-white"><div className="mx-auto mb-4 rounded-2xl bg-white px-5 py-3 shadow-xl"><BrandLogo className="h-16 w-full" priority /></div><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-100">Inspection intelligence</p><h1 className="mt-2 text-3xl font-bold">Welcome to NIRIKSHAK</h1><p className="mt-1 text-sm text-brand-100/80">Compliance screening, made clearer.</p></div><form onSubmit={handleSubmit} className="card space-y-5 p-6 sm:p-7"><div><h2 className="text-xl font-bold text-slate-900">Sign in</h2><p className="mt-1 text-sm text-slate-500">Start a new inspection or review a completed one.</p></div><div><label className="label">Email</label><input type="email" required className="input" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="officer@legalmetrology.gov.in" /></div><div><label className="label">Password</label><input type="password" required className="input" value={password} onChange={(e) => setPassword(e.target.value)} /></div>{error && <p className="text-sm text-red-600">{error}</p>}<button type="submit" disabled={loading} className="btn-primary w-full">{loading ? "Signing in..." : "Sign in to NIRIKSHAK"}</button><p className="rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">Local demo: <span className="font-medium text-slate-700">admin@legalmetrology.gov.in</span> / <span className="font-medium text-slate-700">ChangeMe@123</span></p></form></div></div>;
}
