import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

export default function Login() {
  const { login } = useAuth(); const navigate = useNavigate();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const handleSubmit = async (e) => { e.preventDefault(); setError(""); setLoading(true); try { await login(email, password); navigate("/"); } catch (err) { setError(err.response?.data?.detail || "Login failed. Please check your credentials."); } finally { setLoading(false); } };
  return <div className="min-h-screen flex items-center justify-center bg-brand-900 bg-[radial-gradient(circle_at_top_right,_rgba(96,165,250,.38),_transparent_32%),radial-gradient(circle_at_bottom_left,_rgba(30,64,175,.6),_transparent_40%)] px-4"><div className="w-full max-w-md"><div className="mb-7 text-center text-white"><div className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-white text-sm font-black text-brand-900 shadow-lg">LM</div><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-100">Officer portal</p><h1 className="mt-2 text-3xl font-bold">Legal Metrology</h1><p className="mt-1 text-sm text-brand-100/80">Compliance checking system</p></div><form onSubmit={handleSubmit} className="card space-y-5 p-6 sm:p-7"><div><h2 className="text-xl font-bold text-slate-900">Welcome back</h2><p className="mt-1 text-sm text-slate-500">Sign in to start or review an inspection.</p></div><div><label className="label">Email</label><input type="email" required className="input" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="officer@legalmetrology.gov.in" /></div><div><label className="label">Password</label><input type="password" required className="input" value={password} onChange={(e) => setPassword(e.target.value)} /></div>{error && <p className="text-sm text-red-600">{error}</p>}<button type="submit" disabled={loading} className="btn-primary w-full">{loading ? "Signing in..." : "Sign in"}</button><p className="rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">Local demo: <span className="font-medium text-slate-700">admin@legalmetrology.gov.in</span> / <span className="font-medium text-slate-700">ChangeMe@123</span></p></form></div></div>;
}
